import Head from 'next/head'
import Image from 'next/image'
import { Navbar } from '../components/common/navbar'
import { FocusCate } from '../components/home/focusCate'
import { Pricing } from '../components/home/pricing'
import { Top } from '../components/home/top'
import { TopCate } from '../components/home/topCate'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Top />
      <TopCate />
      <FocusCate />
      <Pricing />
    </>
  )
}
