import Head from 'next/head'
import { Navbar } from '../components/common/navbar'
import { useState, useEffect } from 'react'
import MojoAuth from "mojoauth-web-sdk"




export default function Home() {
  const [payload, setPayload] = useState(null)
  React.useEffect(() => {
    const mojoauth = new MojoAuth("test-3d9558c9-009e-4207-97f8-d84b6f67ed22", {
      source: [{ type: 'email', feature: 'magiclink' }]
    });
    mojoauth.signIn().then(payload => {
      setPayload(payload)
      document.getElementById("mojoauth-passwordless-form").remove();
    })
  }, [])
  return (
    <>
      <div>
        {/* 2 Put a div that will contain the form*/}
        <div id="mojoauth-passwordless-form" />
        <pre>{JSON.stringify(payload, null, 4)}</pre>
      </div>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      {/* <Navbar /> */}
    </>
  )
}
